"""baseline schema

Revision ID: f6d3602a4dad
Revises: 
Create Date: 2026-03-21 01:13:34.713071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d3602a4dad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rollover_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('old_token', sa.String(length=20), nullable=False),
    sa.Column('old_contract', sa.String(length=50), nullable=False),
    sa.Column('new_token', sa.String(length=20), nullable=False),
    sa.Column('new_contract', sa.String(length=50), nullable=False),
    sa.Column('old_expiry', sa.String(length=20), nullable=True),
    sa.Column('new_expiry', sa.String(length=20), nullable=True),
    sa.Column('positions_closed', sa.Integer(), nullable=False),
    sa.Column('rolled_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rollover_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rollover_history_symbol'), ['symbol'], unique=False)

    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_token', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.drop_column('contract_token')

    with op.batch_alter_table('rollover_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rollover_history_symbol'))

    op.drop_table('rollover_history')
    # ### end Alembic commands ###
